fixed formatting
mentorpaired/frontend pull request #51
Opened 2021-01-17 18:45 UTC by FolaDee

2021-01-17 20:21 UTC, Nkoli approved these changes
LGTM but let Tunde also approve before you merge, in case I missed something

2021-01-19 14:42 UTC, toystars requested changes

2021-01-19 14:42 UTC, toystars commented on src/modules/sign/components/gitSignIn.jsx
> +    githubButton.addEventListener("mouseover", function github () {
This is not the correct way of attaching events to components in React. This was mentioned in an earlier PR review. Please adjust.

2021-01-19 14:42 UTC, toystars commented on src/modules/sign/components/gitSignIn.jsx
> +    const gitlabButton = document.getElementById("button2");
Please apply correct spacing to your code to make it more readable.

2021-01-25 23:38 UTC, closed without merging